api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (PurchaseViewSet, IngredientsViewSet, FollowViewSet,
                    FavoriteViewSet)

router_v1 = DefaultRouter()

router_v1.register(r'ingredients', IngredientsViewSet, basename="ingredienst")
router_v1.register(r'subscriptions', FollowViewSet,
                   basename="subscriptions")
router_v1.register(r'favorites', FavoriteViewSet,
                   basename="favorites")
router_v1.register(r'purchases', PurchaseViewSet,
                   basename="purchase")

urlpatterns = [
    path("v1/", include(router_v1.urls)),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage as storage
from django.urls import include, path
from django.views.generic.base import RedirectView

handler404 = "foodgram.views.page_not_found"  # noqa
handler500 = "foodgram.views.server_error"  # noqa
handler403 = "foodgram.views.permission_denied"  # noqa

urlpatterns = [
    path("", include("recipes.urls")),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("api/", include("api.urls")),
    path("favicon.ico", RedirectView.as_view(url=storage.url("favicon.ico"))),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),

    path("recipes/<int:recipe_id>/", views.recipe_view,
         name="recipe_view"),
    path("new/", views.new_view,
         name="recipe_new"),
    path("recipes/<int:recipe_id>/edit/", views.edit_view,
         name="recipe_edit"),
    path("recipes/<int:recipe_id>/delete/", views.delete_view,
         name="recipe_delete"),

    path("favorites/", views.FavoritesView.as_view(), name="favorites"),

    path("purchases/", views.PurchaseView.as_view(), name="purchases_view"),

    path("follows/", views.FollowsView.as_view(), name="follows"),

    path("shoplist/", views.GetShopList.as_view(), name="shoplist"),
]

recipes/models.py
from colorful.fields import RGBColorField
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models

from .managers import FavoriteManager, PurchaseManager
from .utils import random_string

User = get_user_model()

GREEN_COLOR = "#00ff00"
RED_COLOR = "#ff0000"
YELLOW_COLOR = "#ffff00"
BLACK_COLOR = "#000000"


class Tag(models.Model):

    name = models.CharField(max_length=10,
                            verbose_name="время приема")

    color = RGBColorField(colors=[GREEN_COLOR, RED_COLOR, YELLOW_COLOR],
                          max_length=10, verbose_name="цвет тэга")

    color_slug = models.SlugField(default=BLACK_COLOR,
                                  verbose_name="слаг цвета")

    slug = models.SlugField(default=random_string(5),
                            verbose_name="слаг тэга")

    class Meta:
        unique_together = ("name", "color", "color_slug", "slug")
        verbose_name = "тэг"
        verbose_name_plural = "тэги"

    def __str__(self):
        return self.name


class Product(models.Model):

    title = models.CharField(
        max_length=100,
        verbose_name="название"
    )

    dimension = models.CharField(
        max_length=50,
        verbose_name="единица"
    )

    class Meta:
        ordering = ("title", )
        verbose_name = "продукт"
        verbose_name_plural = "продукты"

    def __str__(self):
        return f"{self.title} - {self.dimension}"

    def save(self, *args, **kwargs):
        self.title = self.title.lower()
        return super().save()


class Recipe(models.Model):

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        db_column="author",
        related_name="recipes",
        verbose_name="автор",
    )

    title = models.CharField(
        max_length=50,
        verbose_name="название",
    )

    pub_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name="дата публикации"
    )

    pic = models.ImageField(upload_to="meals/%Y-%m-%d")

    description = models.TextField(verbose_name="описание")

    duration = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name="длительность"
    )

    ingredients = models.ManyToManyField(
        Product,
        related_name="recipes",
        through="Ingredient",
        blank=True,
        verbose_name="ингредиенты"
    )

    slug = models.SlugField(verbose_name="слаг")

    tags = models.ManyToManyField(Tag, verbose_name="тэги")

    class Meta:
        ordering = ("-pub_date", "title",)
        verbose_name = "Рецепт"
        verbose_name_plural = "Рецепты"

    def __str__(self):
        return f"{self.title} - {self.author}"


class Ingredient(models.Model):

    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="recipe_ingredients",
        verbose_name="рецепт"
    )

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="recipe_ingredients",
        verbose_name="продукт"
    )

    quantity = models.PositiveIntegerField(verbose_name="количество")

    class Meta:
        ordering = ("product", )
        verbose_name = "Ингредиент"

    def __str__(self):
        return f"{self.recipe.title} - {self.product.title} - {self.quantity}"


class Favorite(models.Model):

    user = models.ForeignKey(User,
                             related_name="favorites",
                             on_delete=models.CASCADE,
                             verbose_name="пользователь")

    recipes = models.ForeignKey(Recipe,
                                verbose_name="рецепты",
                                on_delete=models.CASCADE,
                                related_name="favorite_recipes")

    objects = FavoriteManager()

    class Meta:
        ordering = ("user", )
        verbose_name = "избранное"
        verbose_name_plural = "избранные"

    def __str__(self):
        return f"{self.user.username} - {self.recipes.title}"


class Follow(models.Model):

    user = models.ForeignKey(
        User,
        related_name="follower",
        on_delete=models.CASCADE,
        verbose_name="последователь"
    )
    author = models.ForeignKey(
        User,
        related_name="followed",
        on_delete=models.CASCADE,
        verbose_name="автор"
    )

    class Meta:
        ordering = ("user", )
        verbose_name = "подписки"

    def __str__(self):
        return (f"Автор {self.author.username}, "
                f"последователь {self.user.username}")


class Purchase(models.Model):

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="purchases",
        verbose_name="пользователь"
    )

    recipes = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="purchases",
        verbose_name="рецепты"
    )

    objects = PurchaseManager()

    class Meta:
        verbose_name = "покупка"
        verbose_name_plural = "покупки"

    def __str__(self):
        ls = ''.join(list(self.objects.list(self.user)))
        return f"Пользователь {self.user.username}, покупки {ls}"

recipes/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Ingredient, Product, Recipe, Tag
from .utils import get_form_ingredients

User = get_user_model()


class RecipeForm(forms.ModelForm):

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={"class": "tags__checkbox"}),
        to_field_name="slug",
        required=True,
    )

    description = forms.CharField(required=True)

    class Meta:

        model = Recipe

        fields = (
            "title", "description", "ingredients",
            "duration", "pic", "tags")

        widgets = {
            "title": forms.TextInput(attrs={"class": "form__input"}),
            "description": forms.Textarea(
                attrs={"class": "form__textarea", "rows": "8"}),
            "duration": forms.NumberInput(
                attrs={"class": "form__input", "id": "id_time",
                       "name": "time"}),
        }

        labels = {
            "image": "Загрузить фото"
        }

    def clean_ingredients(self):

        ingredient_names = [
            self.data[key]
            for key in self.data
            if key.startswith("nameIngredient_")
        ]

        ingredient_units = [
            self.data[key]
            for key in self.data
            if key.startswith("unitsIngredient_")
        ]

        ingredient_quantities = [
            self.data[key]
            for key in self.data
            if key.startswith("valueIngredient_")
        ]

        ingredients_clean = []

        for ingredient in zip(ingredient_names, ingredient_units,
                              ingredient_quantities):
            if not int(ingredient[2]) > 0:
                raise forms.ValidationError("Количество ингредиентов должно "
                                            "быть больше нуля.")
            elif not Product.objects.filter(title=ingredient[0]).exists():
                raise forms.ValidationError(
                    "Ингредиенты должны быть из списка")
            else:
                ingredients_clean.append({"title": ingredient[0],
                                          "unit": ingredient[1],
                                          "quantity": ingredient[2]})

        if len(ingredients_clean) == 0:
            raise forms.ValidationError("Добавьте ингредиент")
        return ingredients_clean

    def save(self, author=None):
        recipe = super().save(commit=False)
        recipe.author = author
        ingredients = self.cleaned_data["ingredients"]
        self.cleaned_data["ingredients"] = []
        recipe = super().save()
        Ingredient.objects.bulk_create(
            get_form_ingredients(ingredients, recipe)
        )
        return recipe

recipes/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.http import require_http_methods

from .forms import RecipeForm
from .models import Follow, Ingredient, Purchase, Recipe, Tag

PER_PAGE = getattr(settings, "PAGINATOR_PER_PAGE", None)

User = get_user_model()


@login_required
@require_http_methods(["GET", "POST"])
def new_view(request):

    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        recipe = form.save(author=request.user)
        return redirect("recipe_view", recipe_id=recipe.id)
    tags = Tag.objects.all()
    context = {
        "page_title": "Создание рецепта",
        "button": "Создать рецепт",
        "tags": tags,
        "form": form,
    }
    return render(request, "recipes/formRecipe.html", context)


@require_http_methods(["GET"])
def recipe_view(request, recipe_id):

    recipe = get_object_or_404(Recipe, id=recipe_id)
    context = {
        "page_title": recipe.title,
        "recipe": recipe,
    }
    return render(request, "recipes/singlePage.html", context)


@login_required
@require_http_methods(["GET"])
def delete_view(request, recipe_id):

    recipe = get_object_or_404(Recipe, id=recipe_id)
    recipe.delete()
    return redirect("index")


@login_required
@require_http_methods(["GET", "POST"])
def edit_view(request, recipe_id):

    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user != recipe.author:
        return redirect("recipe_view", recipe_id=recipe_id)
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        instance=recipe
    )
    if form.is_valid():
        recipe.recipe_ingredients.all().delete()
        form.save(author=request.user)
        return redirect("recipe_view", recipe_id=recipe_id)
    form = RecipeForm(instance=recipe)
    tags = Tag.objects.all()
    context = {
        "page_title": "Редактирование рецепта",
        "button": "Сохранить",
        "tags": tags,
        "form": form,
        "recipe": recipe,
        "edit": True,
    }
    return render(request, "recipes/formRecipe.html", context)


class IndexView(View):

    def get_queryset(self, request):

        tags = request.GET.getlist("filters")
        if not tags:
            recipes = Recipe.objects.exclude(
                tags__slug__in=tags)
        else:
            recipes = Recipe.objects.filter(
                tags__slug__in=tags).distinct()
        return recipes

    def get(self, request, tag_slug=None):

        recipes = self.get_queryset(request)
        paginator = Paginator(recipes, PER_PAGE)
        page_number = request.GET.get("page")
        page = paginator.get_page(page_number)
        tags = Tag.objects.all()
        context = {
            "page_title": "Рецепты",
            "page": page,
            "paginator": paginator,
            "tags": tags,
        }
        return render(
            request,
            "recipes/index.html",
            context
        )


@method_decorator(login_required, name="dispatch")
class FollowsView(View):

    def get(self, request):

        follows = Follow.objects.filter(
            user=request.user).order_by("pk")
        page_num = request.GET.get("page")
        paginator = Paginator(follows, PER_PAGE)
        page = paginator.get_page(page_num)
        context = {
            "page_title": "Мои подписки",
            "active": "subscription",
            "paginator": paginator,
            "page": page,
        }
        return render(request, "recipes/myFollow.html", context)


@method_decorator(login_required, name="dispatch")
class FavoritesView(View):

    def get_queryset(self, request, user):

        tags = request.GET.getlist("filters")
        try:
            if not tags:
                recipes = Recipe.objects.filter(
                    favorite_recipes__user=user).distinct()
            else:
                recipes = Recipe.objects.filter(
                    favorite_recipes__user=user).filter(
                    tags__slug__in=tags)
        except Recipe.DoesNotExist:
            return []
        return recipes

    def get(self, request):

        user = request.user
        recipes = self.get_queryset(request, user)
        # recipes = Recipe.objects.all()
        paginator = Paginator(recipes, PER_PAGE)
        page_number = request.GET.get("page")
        page = paginator.get_page(page_number)
        tags = Tag.objects.all()
        context = {
            "page_title": "Избранное",
            "page": page,
            "paginator": paginator,
            "tags": tags,
        }
        return render(request, "recipes/index.html", context)


@method_decorator(login_required, name="dispatch")
class PurchaseView(View):

    def get(self, request):

        recipes = Purchase.objects.list(user=request.user)
        context = {
            "page_title": "Список покупок",
            "recipes": recipes,
            "active": "purchase",
        }
        return render(request, "recipes/shopList.html", context)


@method_decorator(login_required, name="dispatch")
class GetShopList(View):

    def get(self, request):

        user = request.user
        ingredients = (
            Ingredient.objects.select_related("product").
            filter(recipe__purchases__user=user).
            values("product__title", "product__dimension").
            annotate(total=Sum("quantity"))
        )
        filename = f"{user.username}_list.txt"
        products = []
        for ingredient in ingredients:
            products.append(
                f"{ingredient['product__title']}, "
                f"{ingredient['product__dimension']}, "
                f"{ingredient['total']}"
                "\n"
            )
        content = ''.join(products)
        response = HttpResponse(content, content_type="txt/plain")
        response["Content-Disposition"] = f"attachment; filename={filename}"
        return response

recipes/templates/recipes/buttonFavorite.html
{% load recipes_filters %}

<div class="single-card__favorite">
    {% if request.user.is_authenticated %}
            {% if recipe|favorite:user %}
                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite icon-favorite_active"></span></button>
                <div class="single-card__favorite-tooltip tooltip"></div>
            {% else %}
                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite icon-favorite"></span></button>
                <div class="single-card__favorite-tooltip tooltip"></div>
            {% endif %}
    {% endif %}
</div>

recipes/templates/recipes/buttonSubscribe.html
{% load recipes_filters %}
{% load static %}
{% if follower.is_authenticated %}

    {% if author|subscribed:follower %}
        <button class="button button_style_light-blue button_size_subscribe" name="subscribe" >Отписаться от автора</button></p>
    {% else %}
        {% if not author == follower %}
            <button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></p>
        {% endif %}
    {% endif %}
{% endif %}

recipes/templates/recipes/edit.html
{% extends "base.html" %}
{% block title %}{{ page_title }}{% endblock %}
{% block content %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}
<div class="row justify-content-center">
    <div class="col-md-10 p-5">
        <div class="card">
            {% if form.text|length > 0 %}
                <div class="card-header">Редактировать запись</div>
            {% else %}
                <div class="card-header">Добавить запись</div>
            {% endif %}
            <div class="card-body">
                <form method="post" action='.' enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group row">
                            <label for="{{ field.label }}" class="col-md-4 col-form-label text-md-left">
                                {{ field.label }}
                            </label>
                            <div class="col-md-12">
                                {{ field|addclass:"form-control" }}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">
                            {% if form.text|length > 0 %}
                                Сохранить
                            {% else %}
                                Добавить
                            {% endif %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

recipes/templates/recipes/followItem.html
{% load thumbnail recipes_filters %}
{% load mathfilters %}
<div class="card-user" data-author="{{ follow.author.id }}">
    <div class="card-user__header">
        <h2 class="card-user__title">
            {% if follow.author.first_name %}
                {{ follow.author.first_name }}
            {% else %}
                {{ follow.author.username }}
            {% endif %}
        </h2>
        </a>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
            {% for recipe in follow.author.recipes.all %}
                {% if forloop.counter < 4 %}
                    <li class="card-user__item">
                        <div class="recipe">
                                {% thumbnail recipe.pic "72x72" crop="center" upscale=True as pic %}
                                    <img src="{{ pic.url }}" alt="{{ recipe.title }}" class="recipe__image">
                                {% endthumbnail %}
                                <h3 class="recipe__title">{{ recipe.title }}</h3>
                            <p class="recipe__text"><span class="icon-time"></span> {{ recipe.duration }} мин.</p>
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
            {% if follow.author.recipe.count > 3 %}
                <li class="card-user__item">
                    <a href="{% url 'profile_view' user_id=follow.author.id %}" class="card-user__link link">Еще {{ follow.author.recipe.count|sub:4|abs }} рецептов...</a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="single-card__item">
        {% include 'recipes/buttonSubscribe.html' with follower=request.user author=follow.author %}
    </div>
</div>

{% block javascript %}
{% load static %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/MyFollow.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'myFollow.js' %}"></script>
{% endblock %}

recipes/templates/recipes/formRecipe.html
{% extends "base.html" %}
{% block title %}{{ page_title }}{% endblock %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "pages/form.css" %}">
{% endblock %}

{% block content %}
{% load recipes_filters %}
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">{{ page_title }}</h1>
    </div>
    <div class="form-container">
        <form name=form enctype="multipart/form-data" class="form" action="" method="POST">
            {% csrf_token %}
            <div class="form__group">
                <label for={{ form.title.id_for_label }} class="form__label" required="">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="id_name" name="{{ form.title.name }}" class="form__input"
                        {% if edit %} 
                            value="{{ form.title.value }}"
                        {% endif %}>
                    {% if form.errors %}
                        <span class="form__error">{{ form.title.errors }}</span>
                    {% endif %}
                </div>
            </div>

            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div name=tags class="tags">
                        {% for tag in tags %}
                            <div class="tags__item">
                            <input type="checkbox" name="tags" id="id_{{ tag.slug }}" value="{{ tag.slug }}" class="tags__checkbox tags__checkbox_style_{{ tag.color_slug }}"
                                {% if tag in recipe.tags.all %} checked> {% else %} > {% endif %}
                            <label name="checkbox_label" for="id_id_tags_0" class="tags__label">{{ tag.name|badge_color:tag.color }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    <span class="form__error">{{ form.tags.errors }}</span>
                </div>
            </div>

            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                        {% for ingredient in recipe.recipe_ingredients.all %}
                            <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
                                <span> {{ ingredient.product.title }} {{ ingredient.quantity }} {{ ingredient.product.dimension }} </span>
                                <span class="form__field-item-delete"></span>
                                <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.product.title }}">
                                <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.quantity }}">
                                <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.product.dimension }}">
                            </div>
                        {% endfor %}
                    </div>
                    <div class="form__field-group">
                        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                        <span class="form__error">{{ form.ingredients.errors }}</span>
                    </div>
                </div>
            </div>

            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="number" id="id_time" name="{{ form.duration.name }}" class="form__input" value="{{ form.duration.initial }}" min="0" required="" >
                    <label for="id_time" class="form__label" >минут</label>
                    <span class="form__error">{{ form.duration.errors }}</span>
                </div>
            </div>

            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {% if edit %}
                        <textarea name="description" id="id_description" rows="8" class="form__textarea" required="">{{ form.description.initial }}</textarea>
                    {% else %}
                        <textarea name="description" id="id_description" rows="8" class="form__textarea" required=""></textarea>
                    {% endif %}
                    <span class="form__error">{{ form.description.errors }}</span>
                </div>
            </div>

            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    {{ form.pic.as_widget }}
                    <span class="form__error">{{ form.pic.errors }}</span>
                </div>
            </div>

            <div class="form__footer">
                <input type="submit"p onclick="return((checkboxCheck(tags)) && ingredientCheck(nameIngredient));" class="button button_style_blue" value="{{ button }}">
                {% if recipe.id %}
                    <a style="margin-left: 2.5em" href="{% url "recipe_delete" recipe_id=recipe.id %}" class="form__ingredient-link">Удалить</a>
                {% endif %}
            </div>

        </form>
    </div>
</main>
{% endblock %}

{% block javascript %}
{% load static %}
<script src="{% static "js/config/config.js" %}"></script>
<script src="{% static "js/components/Header.js" %}"></script>
<script src="{% static "js/utils/debouncing.js" %}"></script>
<script src="{% static "js/api/Api.js" %}"></script>
<script src="{% static "formRecipe.js" %}"></script>
{% endblock %}

recipes/templates/recipes/index.html
{% extends "base.html" %}
{% block title %} {{ page_title }} {% endblock %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "pages/index.css" %}">
{% endblock %}
{% block content %}
    {% load recipes_filters %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">{{ page_title }}</h1>
            {% include "recipes/includes/tags.html" %}
        </div>

        <div class="card-list">
                {% for recipe in page %}
                    <div class="card" data-id={{ recipe.id }}>
                        {% include "recipes/includes/previewRecipe.html" with recipe=recipe %}
                    </div>
                {% endfor %}
        </div>
        {% if page.has_other_pages %}
            {% include "includes/paginator.html" with page=page paginator=paginator %}
        {% endif %}
    </main>

{% endblock %}

{% block javascript %}
{% load static %}
    <script src="{% static "js/components/MainCards.js" %}"></script>
    <script src="{% static "js/components/Purchases.js" %}"></script>
    {% if user.is_authenticated %}
    <script src="{% static "js/components/Favorites.js" %}"></script>
    {% endif %}
    <script src="{% static "js/config/config.js" %}"></script>
    <script src="{% static "js/components/CardList.js" %}"></script>
    <script src="{% static "js/components/Header.js"%}"></script>
    <script src="{% static "js/api/Api.js" %}"></script>
    {% if user.is_authenticated %}
        <script src="{% static "indexAuth.js" %}"></script>
    {% else %}
        <script src="{% static "indexNotAuth.js" %}"></script>
    {% endif %}
{% endblock %}

recipes/templates/recipes/myFollow.html
{% extends "base.html" %}
{% block title %}{{ page_title }}{% endblock %}
{% load static %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "pages/myFollow.css" %}">
{% endblock %}

{% block content %}
    {% load static %}
    {% csrf_token %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">{{ page_title }}</h1>
        </div>
        <div class="card-list">
            {% for follow in page %}
                {% include "recipes/includes/followItem.html" with follow=follow %}
            {% empty %}
                <p>Вы еще ни на кого не подписались.</p>
            {% endfor %}
        </div>
        {% if page.has_other_pages %}
            {% include "includes/paginator.html" with page=page paginator=paginator %}
        {% endif %}
    </main>
{% endblock %}

{% block javascript %}
{% load static %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/MyFollow.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'myFollow.js' %}"></script>

{% comment %} <script src="{% static "js/components/SingleCard.js" %}"></script> {% endcomment %}
{% comment %} <script src="{% static "singlePage.js" %}"></script> {% endcomment %}

{% endblock %}